# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'sdk.changers-sampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod "changers-ios-sdk", :git => 'https://github.com/Changers/changers-ios-sdk.git'

end
